name = "cfnote-api"
main = "src/index.ts"
compatibility_date = "2024-03-24"

kv_namespaces = [
  { binding = "NOTES", id = "ebe54ba5987c4702a5cfce445991f007", preview_id = "8a94f9a1425a4816b844e106fcca838b" }
]

[build]
command = "npm run build"

[dev]
port = 8787

[site]
bucket = "./dist"

[observability.logs]
enabled = true
